#!/usr/bin/env python3
"""Build and check the documentation.

This is a *checker* first and a generator second, because the failure this
repository actually has is not a missing docs site — it is documentation that
asserts something the code does not do.

That has happened repeatedly and each time it was invisible in review:

* ``CLAUDE.md`` pointed at ``chief-of-staff-agent-spec.md`` long after the file
  was renamed to ``SPEC.md``.
* ``SPEC.md`` and ``CLAUDE.md`` both described ``title_from_gemini_subject()``
  as resolving the ambiguous-note case while no production path called it.
* A workflow comment claimed "no model reads the source" when Copilot Autofix,
  enabled by default, sends code to one.

A broken link is the cheapest of those to catch mechanically, so this catches
it. The rest still needs a reader — but a reader who trusts the links.

    python3 scripts/build_docs.py           # check, and write docs/api.md
    python3 scripts/build_docs.py --check   # check only, write nothing
"""

from __future__ import annotations

import ast
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PACKAGE = ROOT / "src" / "daydag"
OUT = ROOT / "docs" / "api.md"

#: Markdown links to files in this repo. Anchors and external URLs are excluded:
#: an anchor needs a heading index that drifts, and an external URL needs the
#: network - neither belongs in a check that must be fast and offline.
_LINK = re.compile(r"\[[^\]]*\]\((?!https?://|mailto:|#)([^)\s]+)\)")

#: Documentation that must exist. Enumerated so a file deleted by accident is a
#: failure rather than a silent absence.
REQUIRED_DOCS = ("README.md", "SPEC.md", "ARCHITECTURE.md", "BUILD.md", "CONTRIBUTING.md")


#: Directories the link check does not descend into. ``worktrees`` rather than
#: ``.claude``: `.claude/worktrees/` holds whole checkouts and would be scanned
#: many times over, but `.claude/skills/` is documentation like any other and
#: was silently exempt - a broken link in a SKILL.md sailed through CI.
SKIP_DIRS = frozenset({".git", ".venv", "node_modules", "worktrees"})


def markdown_files() -> list[Path]:
    return sorted(
        path for path in ROOT.rglob("*.md") if not any(part in SKIP_DIRS for part in path.parts)
    )


def check_links() -> list[str]:
    """Every relative markdown link resolves to a file that exists."""
    problems: list[str] = []
    for path in markdown_files():
        for lineno, line in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
            for target in _LINK.findall(line):
                resolved = (path.parent / target.split("#", 1)[0]).resolve()
                if not resolved.exists():
                    rel = path.relative_to(ROOT)
                    problems.append(f"{rel}:{lineno}: broken link -> {target}")
    return problems


def check_required_docs() -> list[str]:
    return [f"missing required doc: {name}" for name in REQUIRED_DOCS if not (ROOT / name).exists()]


def check_modules_documented() -> list[str]:
    """Every shipped module has a docstring, and README lists it.

    The README module table is the one place a newcomer looks to find out what
    exists. A module absent from it is a module nobody knows to read.
    """
    problems: list[str] = []
    readme = (
        (ROOT / "README.md").read_text(encoding="utf-8") if (ROOT / "README.md").exists() else ""
    )
    for path in sorted(PACKAGE.glob("*.py")):
        if path.name.startswith("_"):
            continue
        if not ast.get_docstring(ast.parse(path.read_text(encoding="utf-8"))):
            problems.append(f"{path.relative_to(ROOT)}: no module docstring")
        if f"`{path.stem}`" not in readme:
            problems.append(f"README.md does not mention the `{path.stem}` module")
    return problems


def build_api_reference() -> str:
    """One page from the module docstrings, which are the real design notes here."""
    lines = [
        "# API reference",
        "",
        "> Generated by `scripts/build_docs.py`. Do not edit — change the module",
        "> docstring instead. The docstrings carry the reasoning, not just the",
        "> signature, so this page is the short version of why each module exists.",
        "",
    ]
    for path in sorted(PACKAGE.glob("*.py")):
        if path.name.startswith("_"):
            continue
        doc = ast.get_docstring(ast.parse(path.read_text(encoding="utf-8"))) or "_(undocumented)_"
        lines += [f"## `daydag.{path.stem}`", "", doc.strip(), ""]
    return "\n".join(lines) + "\n"


def main() -> int:
    check_only = "--check" in sys.argv
    problems = check_required_docs() + check_links() + check_modules_documented()

    if problems:
        print("docs check failed:")
        for problem in problems:
            print(f"  {problem}")
        return 1

    if not check_only:
        OUT.parent.mkdir(exist_ok=True)
        OUT.write_text(build_api_reference(), encoding="utf-8")
        print(f"docs ok; wrote {OUT.relative_to(ROOT)}")
    else:
        print("docs ok")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
